ARG ARCHTAG
ARG PROJECT
ARG LOCAL_REGISTRY
FROM ${LOCAL_REGISTRY}${PROJECT}-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-*.sh \
     docker/files/sdrplay/install-lib.*.patch /

RUN export FULL_BUILD=1 && \
    for x in $(ls -1 /install-*.sh | sort -n); do \
      echo "installing $x" && \
      $x || exit 1; \
    done && \
    for x in $(ls -1 /install-*.sh | sort -n); do \
      echo "cleaning $x" && \
      $x clean; \
    done && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm /install-*.sh && \
    rm /install-lib.*.patch

COPY docker/files/services/sdrplay /etc/services.d/sdrplay

COPY docker/scripts/run.sh /

# this build-arg will reset the cache here, so we will have a fresh copy of the files
ARG GIT_HASH=0
RUN echo "$GIT_HASH" > /build-hash
RUN date > /build-date
RUN date +%s > /build-stamp

ADD . /opt/openwebrx
