ARG ARCHTAG
ARG PROJECT
ARG MAKEFLAGS
FROM ${PROJECT}-base:$ARCHTAG

COPY docker/scripts/install-dependencies-perseus.sh /
RUN /install-dependencies-perseus.sh &&\
    rm /install-dependencies-perseus.sh

COPY . /opt/openwebrx
