ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-dependencies-bladerf.sh /
RUN /install-dependencies-bladerf.sh &&\
    rm /install-dependencies-bladerf.sh

COPY . /opt/openwebrx
