ARG ARCHTAG
ARG PROJECT
ARG MAKEFLAGS
FROM ${PROJECT}-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-bladerf.sh /
RUN /install-dependencies-bladerf.sh &&\
    rm /install-dependencies-bladerf.sh

COPY . /opt/openwebrx
