ARG ARCHTAG
ARG PROJECT
ARG MAKEFLAGS
FROM ${PROJECT}-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-plutosdr.sh /
RUN /install-dependencies-plutosdr.sh &&\
    rm /install-dependencies-plutosdr.sh

COPY . /opt/openwebrx
