ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-dependencies-fcdpp.sh /
RUN /install-dependencies-fcdpp.sh &&\
    rm /install-dependencies-fcdpp.sh

COPY . /opt/openwebrx
