ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-airspy.sh /
RUN /install-dependencies-airspy.sh &&\
    rm /install-dependencies-airspy.sh

ADD . /opt/openwebrx
