ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-dependencies-rtlsdr-soapy.sh /
RUN /install-dependencies-rtlsdr-soapy.sh &&\
    rm /install-dependencies-rtlsdr-soapy.sh

COPY . /opt/openwebrx
