ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-uhd.sh /
RUN /install-dependencies-uhd.sh &&\
    rm /install-dependencies-uhd.sh

COPY . /opt/openwebrx
