ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-soapysdr-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-dependencies-plutosdr.sh /
RUN /install-dependencies-plutosdr.sh &&\
    rm /install-dependencies-plutosdr.sh

COPY . /opt/openwebrx
