FROM debian:bullseye-slim
ARG MAKEFLAGS

COPY docker/files/js8call/js8call-hamlib.patch \
     docker/files/wsjtx/wsjtx.patch \
     docker/files/wsjtx/wsjtx-hamlib.patch \
     docker/files/dream/dream.patch \
     docker/files/direwolf/direwolf-hamlib.patch \
     docker/scripts/add-dependencies.sh /
RUN /add-dependencies.sh && \
    rm /add-dependencies.sh && \
    rm /*.patch
COPY docker/scripts/add-owrx-tools.sh /
RUN /add-owrx-tools.sh && \
    rm /add-owrx-tools.sh

COPY docker/files/services/codecserver /etc/services.d/codecserver

ENTRYPOINT ["/init"]

WORKDIR /opt/openwebrx

VOLUME /etc/openwebrx
VOLUME /var/lib/openwebrx

ENV S6_CMD_ARG0="/opt/openwebrx/docker/scripts/run.sh"
CMD []

EXPOSE 8073
