ARG ARCHTAG
ARG PROJECT
ARG MAKEFLAGS
FROM ${PROJECT}-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-fcdpp.sh /
RUN /install-dependencies-fcdpp.sh &&\
    rm /install-dependencies-fcdpp.sh

COPY . /opt/openwebrx
