ARG ARCHTAG
ARG PROJECT
FROM ${PROJECT}-base:$ARCHTAG

COPY docker/scripts/install-dependencies-hpsdr.sh /

RUN /install-dependencies-hpsdr.sh &&\
    rm /install-dependencies-hpsdr.sh

COPY . /opt/openwebrx
