ARG ARCHTAG
ARG PROJECT
ARG MAKEFLAGS
FROM ${PROJECT}-soapysdr-base:$ARCHTAG
ARG MAKEFLAGS

COPY docker/scripts/install-dependencies-hackrf.sh /
RUN /install-dependencies-hackrf.sh &&\
    rm /install-dependencies-hackrf.sh

COPY . /opt/openwebrx
